 ./a.out "" ""
 ./a.out "       str qui commence et finit par du charset  " " "
 ./a.out "       str qui commence par du charset" " "
 ./a.out "   ~    str ~qui~commence par du charset" " ~"
 ./a.out "str ~qui~finit par du charset~~~~" " ~"
 ./a.out "str ~qui~finit par du charset~~~~" ""
 ./a.out "~~str ~qui~finit par du charset~~~~" ""
 ./a.out "" "~ "
 ./a.out "" ""
 ./a.out "           ~~~  ~~ ~ ~" " ~"
 ./a.out "normalement cette strne contient pas de char du charset" "*&^@~"
 ./a.out "normalement cette strne contient pas de char du charset" ""
 ./a.out "normalement cette strne contient pas de char du charset" "_ "
 ./a.out "normalement cette strne contient pas de char du charset &!#@!_!@!_!@*(&!@(*&!@#_!@_!@#(!*&#(!*#!+_@_!__!" "_ "
 ./a.out "normalement cette strne contient pas de char du charset 654984_65_64651_61_6516_51____456_11_61_655  _6546_5165 16_ 6_1 _               _4" "_ "
 ./a.out "____9____" "_ "
 ./a.out "________" "_ "
